INSERT INTO members (
    id,
    first_name,
    last_name,
    birth_date,
    gender,
    address,
    profession,
    phone_number,
    email,
    occupation,
    registration_fee_paid,
    membership_dues_paid
) VALUES
      (
          'm1',
          'Jean',
          'Rakoto',
          '1990-05-10',
          'MALE',
          'Antananarivo',
          'Farmer',
          0341234567,
          'jean@test.com',
          'PRESIDENT',
          true,
          true
      ),
      (
          'm2',
          'Paul',
          'Ranaivo',
          '1988-02-14',
          'MALE',
          'Antsirabe',
          'Farmer',
          0349876543,
          'paul@test.com',
          'VICE_PRESIDENT',
          true,
          true
      ),
      (
          'm3',
          'Marie',
          'Rakoto',
          '1995-07-20',
          'FEMALE',
          'Toamasina',
          'Accountant',
          0324567890,
          'marie@test.com',
          'TREASURER',
          true,
          true
      ),
      (
          'm4',
          'Sarah',
          'Randria',
          '1993-11-11',
          'FEMALE',
          'Fianarantsoa',
          'Secretary',
          0331239876,
          'sarah@test.com',
          'SECRETARY',
          true,
          true
      );
INSERT INTO member_referees (member_id, referee_id) VALUES
                                                        ('m2','m1'),
                                                        ('m3','m1'),
                                                        ('m4','m2');